name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t mini-blog .

    - name: Run tests (optional)
      run: |
        docker run mini-blog php /path/to/test

    - name: Push Docker image to Docker Hub (optional)
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push mini-blog

    - name: Deploy to server (optional)
      run: ssh user@your-server-ip "docker pull mini-blog && docker-compose up -d"
